### PR TITLE
Replace crossing markings PNGs with vector drawables

### PR DESCRIPTION
**Pull request by NyanSten**
Replaced all PNGs with vector drawables. Pictograms were extracted from the background but kept as PNGs.

### CODE REVIEW

**Comment by ravenfeld** [comment]
@StenSoft  Is it difficult to convert to svg? crossing_markings_part_pictograms.png
I'm not a fan of drawables depending on drawable, I find that the day you modify one it affects too many resources. At least in my company the designers avoid it. Do you have any arguments for staying that way?

**Comment by Helium314** [comment]
To me it looks super simple, and it avoids duplicating the path data.
In case such modifications to only a single crossing are necessary, it's still possible to copy the layer content to the new/changed file.

**Comment by NyanSten** [comment]
> Is it difficult to convert to svg? crossing_markings_part_pictograms.png

The pictograms have Bézier curves, my knowledge of SVG paths isn't good enough to convert that.

> I'm not a fan of drawables depending on drawable, I find that the day you modify one it affects too many resources. At least in my company the designers avoid it. Do you have any arguments for staying that way? 

I'm not inclined either way but I found it useful to have separate layers when creating the vectors, like I would do in a graphics editor, the original images are not aligned when displayed side by side, this way I could easily tweak e.g. the width of zebras and the distance between lines and it applied to all the drawables that use them.

**Comment by ravenfeld** [comment]
OK, I'll try to do it with Figma later this week.

**Pull request merged**
